"""Cria estrutura de tabela inicial.

Revision ID: 9a2d5bf0bb2a
Revises: vcsil
Create Date: 2025-07-27 13:18:30.685580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a2d5bf0bb2a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.Column('username', sa.String(length=30),
                              nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              nullable=False)
                    )
    op.create_index(op.f('ix_accounts_username'), 'accounts', ['username'],
                    unique=True)

    op.create_table('targets',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.Column('handle', sa.String(length=30), nullable=False),
                    sa.Column('source_type', sa.String(length=20),
                              nullable=False),
                    sa.Column('source_value', sa.String(length=255),
                              nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              nullable=False)
                    )
    op.create_index(op.f('ix_targets_handle'), 'targets', ['handle'],
                    unique=True)

    op.create_table('action_logs',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('account_id', sa.Integer(), nullable=False),
                    sa.Column('target_id', sa.Integer(), nullable=True),
                    sa.Column('type',
                              sa.Enum('follow', 'unfollow', 'login', 'scan',
                                      name='actiontype'), nullable=False),
                    sa.Column('status',
                              sa.Enum('pending', 'done', 'failed', 'skipped',
                                      name='actionstatus'), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              nullable=False),
                    sa.Column('started_at', sa.DateTime(timezone=True),
                              nullable=True),
                    sa.Column('finished_at', sa.DateTime(timezone=True),
                              nullable=True),
                    sa.Column('error_message', sa.Text(), nullable=True),
                    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'],
                                            ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['target_id'], ['targets.id'],
                                            ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('ix_action_account_created', 'action_logs',
                    ['account_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_action_logs_account_id'), 'action_logs',
                    ['account_id'], unique=False)
    op.create_index(op.f('ix_action_logs_status'), 'action_logs', ['status'],
                    unique=False)
    op.create_index(op.f('ix_action_logs_type'), 'action_logs', ['type'],
                    unique=False)
    op.create_index('ix_action_type_status', 'action_logs', ['type', 'status'],
                    unique=False)
    op.create_table('relationships',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('account_id', sa.Integer(), nullable=False),
                    sa.Column('target_id', sa.Integer(), nullable=False),
                    sa.Column('is_following', sa.Boolean(), nullable=False),
                    sa.Column('followed_back', sa.Boolean(), nullable=False),
                    sa.Column('followed_at', sa.DateTime(timezone=True),
                              nullable=True),
                    sa.Column('follow_back_at', sa.DateTime(timezone=True),
                              nullable=True),
                    sa.Column('unfollowed_at', sa.DateTime(timezone=True),
                              nullable=True),
                    sa.Column('last_checked_at', sa.DateTime(timezone=True),
                              nullable=True),
                    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'],
                                            ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['target_id'], ['targets.id'],
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('account_id', 'target_id',
                                        name='uq_relationship_account_target')
                    )
    op.create_index('ix_relationship_followed_back', 'relationships',
                    ['account_id', 'is_following', 'followed_back'],
                    unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_relationship_followed_back', table_name='relationships')
    op.drop_table('relationships')
    op.drop_index('ix_action_type_status', table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_type'), table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_status'), table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_account_id'), table_name='action_logs')
    op.drop_index('ix_action_account_created', table_name='action_logs')
    op.drop_table('action_logs')
    op.drop_index(op.f('ix_targets_handle'), table_name='targets')
    op.drop_table('targets')
    op.drop_index(op.f('ix_accounts_username'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
